gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    ttl_update: true
    user_identity_field: email
    firewall: api
    token_parameter_name: refreshToken
    cookie:
        enabled: true
        path: / # default value
        domain: null # default value
        http_only: true # default value
        secure: false
        remove_token_from_body: true # default value
