name: pull request event

on: 
    pull_request:
        types: [opened]
    
jobs:
    add:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy pr
              uses: fjogeleit/http-request-action@v1
              with:
                url: 'https://directus.n0safe.space/items/process'
                method: 'POST'
                customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer nLuIN0yW9Pwwfq87fBGQ0oYlOCh3qT5J"}'
                data: '{"projectgetter": "git clone -b ${{github.event.pull_request.head.ref}} https://github.com/N0SAFE/concoursPhoto-g3.git && rsync -vau --remove-source-files ./concoursPhoto-g3/ ./ && rm -r ./concoursPhoto-g3","modifier": [1,2],"init": "npm run init && npm run build:dev", "id": "0124-ci-G3-pr-${{github.event.pull_request.number}}"}'