name: pull request event

on: 
    pull_request:
        types: [synchronize, reopened]
    
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy pr
              uses: fjogeleit/http-request-action@v1
              with:
                url: '${{secrets.N0SAFE_SPACE_DIRECTUS_URL}}/flows/trigger/7c07ca7d-3be0-4a25-b49c-b29d1f45e405'
                method: 'POST'
                customHeaders: '{"Content-Type": "application/json", "Authorization": "${{secrets.N0SAFE_SPACE_DIRECTUS_AUTH}}"}'
                data: '{"process": ["0124-ci-G3-pr-${{github.event.pull_request.number}}"]}'