name: pull request event

on: 
    pull_request:
        types: [opened]
    
jobs:
    add:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy pr
              uses: fjogeleit/http-request-action@v1
              with:
                url: '${{secrets.N0SAFE_SPACE_DIRECTUS_URL}}/items/process'
                method: 'POST'
                customHeaders: '{"Content-Type": "application/json", "Authorization": "${{secrets.N0SAFE_SPACE_DIRECTUS_AUTH}}"}'
                data: '{"projectgetter": "git clone -b ${{github.event.pull_request.head.ref}} https://github.com/N0SAFE/concoursPhoto-g3.git && rsync -vau --remove-source-files ./concoursPhoto-g3/ ./ && rm -r ./concoursPhoto-g3","modifier": [1,2],"init": "npm run init", "id": "0124-ci-G3-pr-${{github.event.pull_request.number}}"}'